use_default_settings: true

server:
  secret_key: "pkjobs-change-this-to-random-string-in-production"
  limiter: false

search:
  safe_search: 0
  autocomplete: ""
  formats:
    - html
    - json

engines:
  - name: google
    engine: google
    weight: 3
  - name: bing
    engine: bing
    weight: 2
  - name: duckduckgo
    engine: duckduckgo
    weight: 2

outgoing:
  request_timeout: 10.0
  useragent_suffix: ""
